FROM python:3.12-alpine

WORKDIR /app

RUN apk add --no-cache \
    build-base \
    gcc \
    musl-dev \
    python3-dev \
    libffi-dev \
    openssl-dev \
    cargo \
    g++ \
    gfortran \
    openblas-dev

RUN pip install flask scikit-learn pandas

COPY ./ /app

EXPOSE 5000